sudo: false
dist: trusty
language:
  - generic
cache:
  - apt

addons:
  apt:
    sources:
        - sourceline: 'deb http://packages.ros.org/ros/ubuntu trusty main'
          key_url: 'http://packages.ros.org/ros.key'
    packages:
        - python-catkin-tools
        - ros-indigo-catkin

script:
    - source /opt/ros/indigo/setup.bash
    - mkdir -p ~/catkin_ws/src
    - cp -r $TRAVIS_BUILD_DIR ~/catkin_ws/src/
    - cd ~/catkin_ws
    - catkin build
