sudo: false
dist: trusty
language:
  - generic
cache:
  - apt

addons:
  apt:
    sources:
        - sourceline: 'deb http://packages.ros.org/ros/ubuntu trusty main'
          key_url: 'http://packages.ros.org/ros.key'
    packages:
        - python-catkin-tools
        - ros-indigo-catkin

script:
    - source /opt/ros/indigo/setup.bash
    - mkdir -p ~/catkin_ws/src
    - cp -r $TRAVIS_BUILD_DIR ~/catkin_ws/src/
    - cd ~/catkin_ws
    - catkin build

before_deploy:
    - cd $TRAVIS_BUILD_DIR/src
    - zip -r pid.zip pid

deploy:
  provider: releases
  api_key:
    secure: E2rhN02sygt7AtElwCToV/oJkfg4BBESAYlapfCDDUYDZ9MgO3MDKM8hPaWTbtASKSOoTfYCBuDRTsoASI2DCUk5nqzRJ3YRrTTV4NZ3qtBouUyBYPfuDRn4z1Nnlf5g8k/namIR7JDUFUq3sHN9qjVrfieX37ZD2qX7wh9k8b8Ogs4Inra1PQ+TH6yIu28xLvuyNEP/xRmCV3jtrjdM76DhqYOA4krtHdgWtepZSzSpeCo423MDwI+/fH28xasAfWV8U/qmOXNUmSxFnfrivvxALKEPq2f0745+ScANEYXQsnn1IxdPfrQGeb/yEFbVxsUfoPa8ApqNJkX6yOm3mn9n/NqWe4IpSOE9CU/fFsHmJEMtW4XIGlaxlid8twZOi1bfhJv+z5x5HwyE5n/1f3N6eor8pvhkQ7MLqjCVgzugyEzBm0raDgi+cI4vuH+ZW/9lsi9jbrycUjaV+vMki0BZlWtzFvpE/Sn0vQhI48v7N8zvf3VIKfsiirkzf2q2mnq5n/2SoHNomFb4NDj18p4v3KiJjsRkDMHiajRjFDPdfBJaU4SGp43nAAU8h7nRg/YYrAfXpAvlEJL7ozFuBfQmmaPtrjOAhYDCG6Kff0p61zHM28E49uf7zMV86S/sUVs1im7iuNMpgLA+uAAlY82OlnILuObgOua35KkIhLs=
  file: src/pid.zip
  on:
    repo: vanderbiltrobotics/lib-pid
