sudo: false

cache:
  - apt

addons:
  apt:
    sources:
        - sourceline: 'deb http://packages.ros.org/ros/ubuntu xenial main'
          key_url: 'http://packages.ros.org/ros.key'
    packages:
        - python-catkin-tools

script:
    - mkdir -p ~/catkin_ws/src
    - cp -r $TRAVIS_BUILD_DIR ~/catkin_ws/src/
    - cd ~/catkin_ws
    - catkin build
